config/routes.rb
Trackit::Application.routes.draw do
  
  get "home/index"
  
  resources :workstations do
    collection do
      get 'import'
      post :import
    end
  end
 
  
  resources :registrations
  resources :ld_import 
  
  resources :users  do 
    resources :registrations
  end
    

  
  
  

  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :active, :displayName, :givenName, :mail, :sAMAccountName, :sn, :telephoneNumber, :userPrincipalName

  # you can call user.registrations to get an array of all ther registrations
  has_many :registrations
  
  # every update is tracked with paper_trail gem. including destroy
  has_paper_trail
  
  validates :mail, :uniqueness => true
  
  validates :mail, :presence => true
  validates :sAMAccountName, :presence => true
  validates :displayName, :presence => true  
  
  # In case some values are not set, we can fill them in automatically
  after_initialize :set_defaults
  def set_defaults
    self.active = true if (self.active.nil?)
  end
  
  # Helper method creates an association with a device
  def register_device(device)
    r = Registration.create()
    r.device = device
    r.user = self
    r.save()
  end
  
  # most functionality should go in a controller, not here! Separation of concerns :)
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-stripe">
  <tr>
    <th>Username</th>
    <th>Phone</th>
    <th>Last changed</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.sAMAccountName %></td>
    <td><%= user.telephoneNumber %></td>
    <td><%= user.updated_at %></td>
    <td><%= link_to 'View devices', user_registrations_path(user), :class => "btn btn-mini"  %></td>
    <td><%= link_to 'Show', user, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>