config/routes.rb
Trackit::Application.routes.draw do
  
  get "home/index"
  
  resources :workstations do
    collection do
      get 'import'
      post :import
    end
  end
 
  
  resources :registrations
  resources :ld_import 
  
  resources :users  do 
    resources :registrations
  end
    

  
  
  

  

  root :to => 'home#index'

end

app/models/workstation.rb
class Workstation < ActiveRecord::Base  
  attr_accessible :serial, :OS, :information, :model, :name
  
  store :information, accessors: [ :last_seen, :primary_user_id ]
  
  # This lets you assign the workstation in a registration:
  has_many :registrations, :as => :device
  
  has_paper_trail
  
  
  def machine_hash(headers,rows)
    # This is just to give a nice data structure (a hash of )
    rows.each_with_index.map do |row, index|
      # todo - rearrange the hash so it is sorted - do we need the row index?
      Hash[headers.each_with_index.map { |header, pos| 
        [header, row[pos] ]}
      ].merge('row' => index+2)
    end
  end
  
  
  # Class method for importing a Landesk CSV

  def self.import(file)
    filedata = file.read
    lines = []
    IO.foreach(file.path) do |line|
      lines << line
    end
    # For some reason I get a quote error for the first line
    lines[0] = lines[0].delete('"')
    
    # Now swap the column headers for my mappings
    mappings = {}
    mappings['Device Name'] = "name"
    mappings['OS Name'] = "OS"
    mappings['Board Name'] = "model"
    mappings['Serial Number'] = "serial"
    
    
    headers = lines.first
    mappings.each do |orig,rep|
      headers.gsub!(/#{orig}/, rep)
    end
    
    lines[0] = headers
    
    # This gives us a hash from column name to data for each row
    data = CSV.parse(lines.join, headers: true)
    
  
    ActiveRecord::Base.transaction do
      logger.info("Beginning Import of workstations")
      
      data.each do |machine|
        serial = machine["serial"]
        ws = find_by_serial(serial) || new
        
        ws.attributes = machine.to_hash.slice(*accessible_attributes)
        #TODO: work out why I can't just query the string
        ws.name= machine[machine.to_hash.keys.first]
        
        # ws.primary_user_id
        ws.save!
      end

    end
  rescue CSV::MalformedCSVError
    debugger
  end
end

app/controllers/workstations_controller.rb
class WorkstationsController < ApplicationController
  # GET /workstations
  # GET /workstations.json
  def index
   
   # this will be a hash of params and their values
   # e.g. model => MacBookPro4,1
    @filters = params.except("action","controller")
    
   
    # there must be a nicer way to do this?
    if @filters.keys.include?("model")
      @workstations = Workstation.where("model = ?", @filters.fetch("model"))
      
    elsif @filters.keys.include?("OS")
      @workstations = Workstation.where("OS = ?", @filters.fetch("OS"))
    else
      @workstations = Workstation.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workstations }
    end
  end
  

  # GET /workstations/1
  # GET /workstations/1.json
  def show
    @workstation = Workstation.find(params[:id])

    @versions = @workstation.versions

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workstation }
    end
  end

  # GET /workstations/new
  # GET /workstations/new.json
  def new
    @workstation = Workstation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workstation }
    end
  end

  # GET /workstations/1/edit
  def edit
    @workstation = Workstation.find(params[:id])
  end

  # POST /workstations
  # POST /workstations.json
  def create
    @workstation = Workstation.new(params[:workstation])

    respond_to do |format|
      if @workstation.save
        format.html { redirect_to @workstation, notice: 'Workstation was successfully created.' }
        format.json { render json: @workstation, status: :created, location: @workstation }
      else
        format.html { render action: "new" }
        format.json { render json: @workstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workstations/1
  # PUT /workstations/1.json
  def update
    @workstation = Workstation.find(params[:id])

    respond_to do |format|
      if @workstation.update_attributes(params[:workstation])
        format.html { redirect_to @workstation, notice: 'Workstation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workstations/1
  # DELETE /workstations/1.json
  def destroy
    @workstation = Workstation.find(params[:id])
    @workstation.destroy

    respond_to do |format|
      format.html { redirect_to workstations_url }
      format.json { head :no_content }
    end
  end
  
  def import
    Workstation.import(params[:file])
    redirect_to root_url, notice: "Workstations imported"
  end
end

app/helpers/workstations_helper.rb
module WorkstationsHelper
end

app/views/workstations/_form.html.erb
<%= simple_form_for(@workstation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
      <%= f.input :serial %>
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.input :OS %>
      
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/workstations/edit.html.erb
<h1>Editing workstation</h1>

<%= render 'form' %>

<%= link_to 'Show', @workstation %> |
<%= link_to 'Back', workstations_path %>

app/views/workstations/import.html.erb
<h3>Import from CSV</h3>
<%= @ld_import.errors.full_messages.to_sentence  %>
<%= simple_form_for :import, :url => '/workstations/import', :html => {:multipart => true}, :class => "form-horizontal" do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :spreadsheet %>
  <%= f.file_field :spreadsheet %>
 <%= f.button :submit, label: "Submit" %>
<% end %>

app/views/workstations/index.html.erb
<h1>Listing workstations</h1>

<% if @filters.keys.length > 0 %>
<h5>Results filtered:</h5>
<% @filters.each do |parm,val| %>
<%= "#{parm.capitalize}: #{val}" %>
<br/>
<% end %>
<p><%= link_to 'Show all workstations', workstations_path, :class => "btn" %></p>
<% end %>
<table class="table table-stripe table-bordered">
  <tr>
    <th>Name</th>
    <th>Model</th>
    <th>OS</th>
    <th>Serial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workstations.each do |workstation| %>
  <tr>
    <td><%= link_to workstation.name, workstation %></td>
    <td><%= workstation.model %> <%= link_to "Filter", workstations_path(:model => workstation.model), :class => "btn btn-small" %></td>
    <td><%= workstation.OS %> <%= link_to "Filter", workstations_path(:OS => workstation.OS), :class => "btn btn-small" %></td>
    <td><%= workstation.serial %></td>
    <td><%= link_to 'Show', workstation, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_workstation_path(workstation), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', workstation, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workstation', new_workstation_path, :class => 'btn' %>

<%= form_tag import_workstations_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end #link_to 'Import LanDesk CSV', import_workstations_path, :class => 'btn' %>

app/views/workstations/new.html.erb
<h1>New workstation</h1>

<%= render 'form' %>

<%= link_to 'Back', workstations_path %>

app/views/workstations/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Workstation details: <%= @workstation.name %></h2>

<ul>
    <li>Serial: <%= @workstation.serial %></li>
    <li>OS: <%= @workstation.OS %></li>
    <li>Model: <%= @workstation.model %> (find more)</li>
    <li>Last seen: <%= @workstation.last_seen %></li>
</ul>
<h4>Registration history</h4>
<table class="table">
    <tr>
        <th>User</th>
        <th>Start time</th>
    </tr>
<% @workstation.registrations.each do |reg| %>

 
    <tr>
        <td><%= reg.user.sAMAccountName  %>
        </td>
        <td><%= reg.created_at %>
        </td>
    </tr>

<% end %>
</table>

<h4>Previous versions</h4>
<p>If this workstation has been changed, the earlier versions are saved. You can view the events affecting this machine below:</p>
<table class="table">
    <tr>

        <th>Date</th>
        <th>Event</th>
    </tr>
<% @versions.each do |ver| %> 
    <tr>
        <td><%= ver.created_at %>
        </td>
        <td><%= ver.event %>
        </td>
    </tr>

<% end %>
</table>

<%= link_to 'Edit', edit_workstation_path(@workstation) %> |
<%= link_to 'Back', workstations_path %>