config/routes.rb
Trackit::Application.routes.draw do
  
  get "home/index"
  
  resources :workstations do
    collection do
      get 'import'
      post :import
    end
  end
 
  
  resources :registrations
  resources :ld_import 
  
  resources :users  do 
    resources :registrations
  end
    

  
  
  

  

  root :to => 'home#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "TrackIT", root_path, :class => 'brand' %>


<ul class="nav">
<li><%= link_to "Workstations", workstations_path %></li>
<li><%= link_to "Users", users_path %></li>
<li><%= link_to "Registrations", registrations_path %></li>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "AdPeople TrackIT" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    </nav>
	<header class="navbar navbar-fixed-top">
	      
	    </header>
        
        <div class="container-fluid">
        
	    <div id="main" role="main">
	   
	        <div class="content">
	           <div class="row-fluid">
	            <div class="span12">
	              <%= render 'layouts/messages' %>
	              <%= yield %>
	            </div>
	          </div>
	          <footer>
	          </footer>
	        </div>
	     
	    </div> <!--! end of #main -->
        
    </div>

</body>
</html>